version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/common/php-fpm
    volumes:
      - ./app:/var/www/app
      - ./.env:/var/www/.env
      - ./storage:/var/www/storage
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./vendor:/var/www/vendor

  nginx:
    build:
      context: ./docker/deployment/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - php-fpm

networks:
  default:
    name: laravel
