name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PHP-FPM image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/common/php-fpm
          file: ./docker/common/php-fpm/Dockerfile
          push: true
          tags: asdin1996/laravel:latest
